### ISSUE TITLE
how to compile it on windows

### ISSUE THREAD

**Issue by fangzhangmnm** [jia-zhuang/chinese-llama2.c#2]
What is win.h? I cannot find anything about it on the internet

**Comment by fangzhangmnm** [comment]
https://github.com/xunboo/llama2win

just copy the mmap-windows.c from this repo and change the run.c:

```c
#if defined _WIN32
    // #include "win.h"
    #include <stdint.h>
    #include "mmap-windows.c"
#else
```

**Comment by zhangtj1996** [comment]
I met with the following error when run the `compile_windows.bat`
run.c: In function 'setConsoleToUTF8':
run.c:928:19: error: 'ENABLE_VIRTUAL_TERMINAL_PROCESSING' undeclared (first use in this function)
         dwMode |= ENABLE_VIRTUAL_TERMINAL_PROCESSING;
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
run.c:928:19: note: each undeclared identifier is reported only once for each function it appears in


Solved by adding the following in run.c:

#ifndef ENABLE_VIRTUAL_TERMINAL_PROCESSING
#define ENABLE_VIRTUAL_TERMINAL_PROCESSING 0x0004
#endif
